bus_data = [
    # Kathmandu to Pokhara Route
    {
        "bus_number": "BA 1 KH 2023",
        "bus_model": "Volvo 9400",
        "service_company": "Sajha Yatayat",
        "driver_name": "Ram Kumar Shrestha",
        "route": {"start": "Kathmandu", "end": "Pokhara"},
        "seat_capacity": 40,
        "seat_available": 35,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.9,
        "price": 1000
    },
    {
        "bus_number": "BA 2 KH 1234",
        "bus_model": "Scania K410",
        "service_company": "Nepal Yatayat",
        "driver_name": "Hari Bahadur Thapa",
        "route": {"start": "Kathmandu", "end": "Pokhara"},
        "seat_capacity": 35,
        "seat_available": 30,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.5,
        "price": 2000
    },
    {
        "bus_number": "BAR 1 KH 2023",
        "bus_model": "Vlvo 9400",
        "service_company": "Sajha Yatayat",
        "driver_name": "Ram Kumar Shrestha",
        "route": {"start": "Kathmandu", "end": "Pokhara"},
        "seat_capacity": 40,
        "seat_available": 36,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.8,
        "price": 1000
    },
    {
        "bus_number": "BA 1 KH 2023",
        "bus_model": "Volvo 9400",
        "service_company": "Pokhara Yatayat",
        "driver_name": "Ram Kumar Shrestha",
        "route": {"start": "Kathmandu", "end": "Pokhara"},
        "seat_capacity": 30,
        "seat_available": 25,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.8,
        "price": 1400
    },
    {
        "bus_number": "BA 1 KH 2023",
        "bus_model": "Volvo 9400",
        "service_company": "Non-Stop Yatayat",
        "driver_name": "Ram Kumar Shrestha",
        "route": {"start": "Kathmandu", "end": "Pokhara"},
        "seat_capacity": 40,
        "seat_available": 38,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.8,
        "price": 1000
    },
    {
        "bus_number": "BA 1 KH 2023",
        "bus_model": "Volvo 9400",
        "service_company": "Express Yatayat",
        "driver_name": "Ram Kumar Shrestha",
        "route": {"start": "Kathmandu", "end": "Pokhara"},
        "seat_capacity": 40,
        "seat_available": 37,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.8,
        "price": 1000
    },
    {
        "bus_number": "BA 3 KH 5678",
        "bus_model": "Volvo 9400",
        "service_company": "Mountain Express",
        "driver_name": "Shyam Gurung",
        "route": {"start": "Kathmandu", "end": "Pokhara"},
        "seat_capacity": 40,
        "seat_available": 34,
        "ac": True,
        "wifi": True,
        "date": "2024-12-02",
        "rating": 4.7,
        "price": 1000
    },
    # Pokhara to Kathmandu Route
    {
        "bus_number": "GA 1 KH 9012",
        "bus_model": "Scania K410",
        "service_company": "Sajha Yatayat",
        "driver_name": "Bikash Tamang",
        "route": {"start": "Pokhara", "end": "Kathmandu"},
        "seat_capacity": 35,
        "seat_available": 28,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.6,
        "price": 1000
    },
    {
        "bus_number": "GA 2 KH 3456",
        "bus_model": "Volvo 9400",
        "service_company": "Mountain Express",
        "driver_name": "Rajesh Magar",
        "route": {"start": "Pokhara", "end": "Kathmandu"},
        "seat_capacity": 40,
        "seat_available": 32,
        "ac": True,
        "wifi": True,
        "date": "2024-12-02",
        "rating": 4.9,
        "price": 1000
    },
    # Kathmandu to Biratnagar Route
    {
        "bus_number": "BA 4 KH 7890",
        "bus_model": "Scania K360",
        "service_company": "Nepal Yatayat",
        "driver_name": "Krishna Sharma",
        "route": {"start": "Kathmandu", "end": "Biratnagar"},
        "seat_capacity": 38,
        "seat_available": 30,
        "ac": True,
        "wifi": False,
        "date": "2024-12-01",
        "rating": 4.9,
        "price": 2200
    },
    {
        "bus_number": "BA 5 KH 1111",
        "bus_model": "Volvo 9400",
        "service_company": "Sajha Yatayat",
        "driver_name": "Binod Adhikari",
        "route": {"start": "Kathmandu", "end": "Biratnagar"},
        "seat_capacity": 40,
        "seat_available": 35,
        "ac": True,
        "wifi": True,
        "date": "2024-12-02",
        "rating": 3.7,
        "price": 1000
    },
    # Biratnagar to Kathmandu Route
    {
        "bus_number": "KO 1 KH 2222",
        "bus_model": "Scania K410",
        "service_company": "Mountain Express",
        "driver_name": "Suman Rai",
        "route": {"start": "Biratnagar", "end": "Kathmandu"},
        "seat_capacity": 35,
        "seat_available": 29,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.5,
        "price": 1900
    },
    {
        "bus_number": "KO 2 KH 3333",
        "bus_model": "Volvo 9400",
        "service_company": "Nepal Yatayat",
        "driver_name": "Deepak Karki",
        "route": {"start": "Biratnagar", "end": "Kathmandu"},
        "seat_capacity": 40,
        "seat_available": 36,
        "ac": True,
        "wifi": True,
        "date": "2024-12-02",
        "rating": 4.6,
        "price": 1900
    },
    # Kathmandu to Lumbini Route
    {
        "bus_number": "BA 6 KH 4444",
        "bus_model": "Scania K360",
        "service_company": "Lumbini Express",
        "driver_name": "Ramesh Poudel",
        "route": {"start": "Kathmandu", "end": "Lumbini"},
        "seat_capacity": 38,
        "seat_available": 33,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.4,
        "price": 2200
    },
    {
        "bus_number": "BA 7 KH 5555",
        "bus_model": "Tata Magna",
        "service_company": "Buddha Express",
        "driver_name": "Kamal Thapa",
        "route": {"start": "Kathmandu", "end": "Lumbini"},
        "seat_capacity": 32,
        "seat_available": 28,
        "ac": False,
        "wifi": True,
        "date": "2024-12-02",
        "rating": 4.0,
        "price": 2900
    },
    # Lumbini to Kathmandu Route
    {
        "bus_number": "NA 1 KH 6666",
        "bus_model": "Scania K410",
        "service_company": "Lumbini Express",
        "driver_name": "Anil Shrestha",
        "route": {"start": "Lumbini", "end": "Kathmandu"},
        "seat_capacity": 35,
        "seat_available": 30,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.5,
        "price": 1900
    },
    {
        "bus_number": "NA 2 KH 7777",
        "bus_model": "Volvo 9400",
        "service_company": "Buddha Express",
        "driver_name": "Prakash Gurung",
        "route": {"start": "Lumbini", "end": "Kathmandu"},
        "seat_capacity": 40,
        "seat_available": 35,
        "ac": True,
        "wifi": True,
        "date": "2024-12-02",
        "rating": 4.8,
        "price": 1900
    },
    # Pokhara to Lumbini Route
    {
        "bus_number": "GA 3 KH 8888",
        "bus_model": "Tata Magna",
        "service_company": "Buddha Express",
        "driver_name": "Santosh KC",
        "route": {"start": "Pokhara", "end": "Lumbini"},
        "seat_capacity": 32,
        "seat_available": 27,
        "ac": False,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.1,
        "price": 2900
    },
    {
        "bus_number": "GA 4 KH 9999",
        "bus_model": "Scania K360",
        "service_company": "Lumbini Express",
        "driver_name": "Dipak Tamang",
        "route": {"start": "Pokhara", "end": "Lumbini"},
        "seat_capacity": 38,
        "seat_available": 33,
        "ac": True,
        "wifi": False,
        "date": "2024-12-02",
        "rating": 4.3,
        "price": 2900
    },
    # Lumbini to Pokhara Route
    {
        "bus_number": "NA 3 KH 1212",
        "bus_model": "Scania K410",
        "service_company": "Mountain Express",
        "driver_name": "Rajan Maharjan",
        "route": {"start": "Lumbini", "end": "Pokhara"},
        "seat_capacity": 35,
        "seat_available": 30,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.6,
        "price": 1900
    },
    {
        "bus_number": "NA 4 KH 3434",
        "bus_model": "Volvo 9400",
        "service_company": "Buddha Express",
        "driver_name": "Mohan Thapa",
        "route": {"start": "Lumbini", "end": "Pokhara"},
        "seat_capacity": 40,
        "seat_available": 35,
        "ac": True,
        "wifi": True,
        "date": "2024-12-02",
        "rating": 4.7,
        "price": 1900
    },
    # Biratnagar to Sikkim Route
    {
        "bus_number": "KO 3 KH 5656",
        "bus_model": "Scania K360",
        "service_company": "Himalayan Travels",
        "driver_name": "Gopal Sharma",
        "route": {"start": "Biratnagar", "end": "Sikkim"},
        "seat_capacity": 38,
        "seat_available": 32,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.4,
        "price": 2200
    },
    {
        "bus_number": "KO 4 KH 7878",
        "bus_model": "Volvo 9400",
        "service_company": "Mountain Express",
        "driver_name": "Nabin Bhattarai",
        "route": {"start": "Biratnagar", "end": "Sikkim"},
        "seat_capacity": 40,
        "seat_available": 35,
        "ac": True,
        "wifi": True,
        "date": "2024-12-02",
        "rating": 3.8,
        "price": 1000
    },
    # Sikkim to Biratnagar Route
    {
        "bus_number": "SK 1 KH 9090",
        "bus_model": "Scania K410",
        "service_company": "Himalayan Travels",
        "driver_name": "Suresh Limbu",
        "route": {"start": "Sikkim", "end": "Biratnagar"},
        "seat_capacity": 35,
        "seat_available": 30,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.5,
        "price": 1900
    },
    {
        "bus_number": "SK 2 KH 1313",
        "bus_model": "Volvo 9400",
        "service_company": "Mountain Express",
        "driver_name": "Bikram Rai",
        "route": {"start": "Sikkim", "end": "Biratnagar"},
        "seat_capacity": 40,
        "seat_available": 36,
        "ac": True,
        "wifi": True,
        "date": "2024-12-02",
        "rating": 4.7,
        "price": 1000
    },
    # Kathmandu to Darjeeling Route
    {
        "bus_number": "BA 8 KH 2424",
        "bus_model": "Volvo 9400",
        "service_company": "Himalayan Travels",
        "driver_name": "Sanjay Lama",
        "route": {"start": "Kathmandu", "end": "Darjeeling"},
        "seat_capacity": 40,
        "seat_available": 35,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.9,
        "price": 1000
    },
    {
        "bus_number": "BA 9 KH 3535",
        "bus_model": "Scania K410",
        "service_company": "Mountain Express",
        "driver_name": "Rajendra Shrestha",
        "route": {"start": "Kathmandu", "end": "Darjeeling"},
        "seat_capacity": 35,
        "seat_available": 30,
        "ac": True,
        "wifi": True,
        "date": "2024-12-02",
        "rating": 4.6,
        "price": 1000
    },
    # Darjeeling to Kathmandu Route
    {
        "bus_number": "WB 1 KH 4646",
        "bus_model": "Volvo 9400",
        "service_company": "Himalayan Travels",
        "driver_name": "Prabin Tamang",
        "route": {"start": "Darjeeling", "end": "Kathmandu"},
        "seat_capacity": 40,
        "seat_available": 36,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.8,
        "price": 1000
    },
    {
        "bus_number": "WB 2 KH 5757",
        "bus_model": "Scania K410",
        "service_company": "Mountain Express",
        "driver_name": "Ashok Kumar",
        "route": {"start": "Darjeeling", "end": "Kathmandu"},
        "seat_capacity": 35,
        "seat_available": 30,
        "ac": True,
        "wifi": True,
        "date": "2024-12-02",
        "rating": 4.7,
        "price": 1000
    },
    # Pokhara to Darjeeling Route
    {
        "bus_number": "GA 5 KH 6868",
        "bus_model": "Volvo 9400",
        "service_company": "Himalayan Travels",
        "driver_name": "Dinesh Gurung",
        "route": {"start": "Pokhara", "end": "Darjeeling"},
        "seat_capacity": 40,
        "seat_available": 35,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.6,
        "price": 1000
    },
    {
        "bus_number": "GA 6 KH 7979",
        "bus_model": "Scania K410",
        "service_company": "Mountain Express",
        "driver_name": "Sujan Thapa",
        "route": {"start": "Pokhara", "end": "Darjeeling"},
        "seat_capacity": 35,
        "seat_available": 30,
        "ac": True,
        "wifi": True,
        "date": "2024-12-02",
        "rating": 4.5,
        "price": 1000
    },
    # Darjeeling to Pokhara Route
    {
        "bus_number": "WB 3 KH 8080",
        "bus_model": "Volvo 9400",
        "service_company": "Himalayan Travels",
        "driver_name": "Roshan Rai",
        "route": {"start": "Darjeeling", "end": "Pokhara"},
        "seat_capacity": 40,
        "seat_available": 36,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.7,
        "price": 1000
    },
    {
        "bus_number": "WB 4 KH 9191",
        "bus_model": "Scania K410",
        "service_company": "Mountain Express",
        "driver_name": "Kiran Magar",
        "route": {"start": "Darjeeling", "end": "Pokhara"},
        "seat_capacity": 35,
        "seat_available": 30,
        "ac": True,
        "wifi": True,
        "date": "2024-12-02",
        "rating": 4.6,
        "price": 1000
    },
    # Lumbini to Sikkim Route
    {
        "bus_number": "NA 5 KH 1414",
        "bus_model": "Volvo 9400",
        "service_company": "Himalayan Travels",
        "driver_name": "Bishnu Prasad",
        "route": {"start": "Lumbini", "end": "Sikkim"},
        "seat_capacity": 40,
        "seat_available": 35,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.5,
        "price": 1000
    },
    {
        "bus_number": "NA 6 KH 2525",
        "bus_model": "Scania K410",
        "service_company": "Mountain Express",
        "driver_name": "Hem Bahadur",
        "route": {"start": "Lumbini", "end": "Sikkim"},
        "seat_capacity": 35,
        "seat_available": 30,
        "ac": True,
        "wifi": True,
        "date": "2024-12-02",
        "rating": 4.4,
        "price": 1000
    },
    # Sikkim to Lumbini Route
    {
        "bus_number": "SK 3 KH 3636",
        "bus_model": "Volvo 9400",
        "service_company": "Himalayan Travels",
        "driver_name": "Gyan Bahadur",
        "route": {"start": "Sikkim", "end": "Lumbini"},
        "seat_capacity": 40,
        "seat_available": 36,
        "ac": True,
        "wifi": True,
        "date": "2024-12-01",
        "rating": 4.6,
        "price": 1000
    },
    {
        "bus_number": "SK 4 KH 4747",
        "bus_model": "Scania K410",
        "service_company": "Mountain Express",
        "driver_name": "Tek Bahadur",
        "route": {"start": "Sikkim", "end": "Lumbini"},
        "seat_capacity": 35,
        "seat_available": 30,
        "ac": True,
        "wifi": True,
        "date": "2024-12-02",
        "rating": 4.5,
        "price": 1000
    },
    # Additional buses for popular routes
    {
        "bus_number": "BA 10 KH 5858",
        "bus_model": "Volvo 9400",
        "service_company": "Sajha Yatayat",
        "driver_name": "Hari Krishna",
        "route": {"start": "Kathmandu", "end": "Pokhara"},
        "seat_capacity": 40,
        "seat_available": 35,
        "ac": True,
        "wifi": True,
        "date": "2024-12-03",
        "rating": 4.8,
        "price": 1000
    },
    {
        "bus_number": "BA 11 KH 6969",
        "bus_model": "Scania K410",
        "service_company": "Nepal Yatayat",
        "driver_name": "Ram Prasad",
        "route": {"start": "Kathmandu", "end": "Biratnagar"},
        "seat_capacity": 35,
        "seat_available": 30,
        "ac": True,
        "wifi": True,
        "date": "2024-12-03",
        "rating": 4.7,
        "price": 1000
    },
    {
        "bus_number": "GA 7 KH 7070",
        "bus_model": "Volvo 9400",
        "service_company": "Mountain Express",
        "driver_name": "Shiva Kumar",
        "route": {"start": "Pokhara", "end": "Kathmandu"},
        "seat_capacity": 40,
        "seat_available": 36,
        "ac": True,
        "wifi": True,
        "date": "2024-12-03",
        "rating": 4.9,
        "price": 1000
    },
    {
        "bus_number": "KO 5 KH 8181",
        "bus_model": "Scania K410",
        "service_company": "Himalayan Travels",
        "driver_name": "Bhim Bahadur",
        "route": {"start": "Biratnagar", "end": "Kathmandu"},
        "seat_capacity": 35,
        "seat_available": 30,
        "ac": True,
        "wifi": True,
        "date": "2024-12-03",
        "rating": 4.6,
        "price": 1000
    }
]

# Sort buses by date and rating
bus_data.sort(key=lambda x: (x['date'], -x['rating'])) 